include: package:pedantic/analysis_options.yaml

analyzer:
  enable-experiment:
    - extension-methods
  errors:
    todo: ignore
    unnecessary_new: ignore
    unnecessary_const: ignore
    unused_local_variable: ignore
  exclude:
    - test/
    - test/**.*
    - test_driver/
    - lib/**.g.dart
    - flare_dart/
    - flare_flutter/

linter:
  rules:
    - flutter_style_todos
    - always_declare_return_types
    - camel_case_types
    - empty_constructor_bodies
    - annotate_overrides
    - avoid_init_to_null
    - constant_identifier_names
    # - one_member_abstracts
    - slash_for_doc_comments
    # - sort_constructors_first
    - unnecessary_brace_in_string_interps
